version: 2.1
orbs:
  appdome-orb: appdome/build-2secure@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

executors:
  my-executor:
    docker:
      - image: cimg/python:3.11.3
    # working_directory: /tmp

jobs:
  downstream:
    executor: my-executor
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ${HOME}/appdome_workspace/

      - run: |
            PARAM=$(circleci eval "$ARTIFACTS_LOCATION")
            echo "$PARAM"

workflows:
  test-deploy:
    jobs:
      - appdome-orb/appdome_runner:
          name: "test-android-auto-sign"
          runner: "ANDROID_AUTO_SIGNING"
          team-id: "81bdde00-a0a7-11ed-a4f2-810d8884a7b1"
          appFile: "https://github.com/idanhauser/TestAppdome_orb_private/raw/main/files/TimeCard1.apk"
          output: "appname.apk"
          filters: *filters
      - downstream:
          filters: *filters
          requires:
            - test-android-auto-sign
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: appdome/build-2secure
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
