version: 2.1
orbs:
  appdome-orb: appdome/appdome-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      # Run your orb's commands to validate them.
      #- appdome-orb/appdome_runner
workflows:
  test-deploy:
    jobs:
      parameters:
        runner:
          description: >
            Choose which fusing operation you want to perfom, on which paltform (iOS or Android)
            and type of sign.
          type: enum
          enum:
            - "ANDROID_AUTO_SIGNING"
            - "ANDROID_PRIVATE_SIGNING"
            - "ANDROID_AUTO_DEV_SIGNING"
            - "IOS_AUTO_SIGNING"
            - "IOS_PRIVATE_SIGNING"
            - "IOS_AUTO_DEV_SIGNING"
        appFile:
          type: string
          description: "Absolute path to your app"
        fusion-set-id:
          type: string
          description: "Fusion Set with the features you want to add to your application."
        output:
          type: string
          description: "The name of the output fused app."
        sign-overrides:
          type: string
          default: ""
          description: "sign overrides"
        # ANDROID PRIVATE SIGN
        signing-fingerprint:
          type: string
          default: ""
          description: "Your unique signing certificate fingerprint is required to tamper-proof Built applications."
        google-play-signing:
          type: boolean
          default: false
          description: "This application will be distributed via the Google Play App Signing program."
        # ANDROID AUTO SIGN
        keystore-file:
          type: string
          default: ""
          description: "iOS: A P12 certificate file is a certificate and private key concatenated into a single file, protected by a password.
          Android: This should be the same keystore file used to sign your Android app when distributing it via Google Play"
        keystore-password:
          type: string
          default: ""
          description: "The password used to unlock your P12 certificate file/keystore."
        keystore-alias:
          type: string
          default: ""
          description: "The name you assigned to your keystore"
        keystore-key-password:
          type: string
          default: ""
          description: "This is the specific password defined for your signing key."
        #IOS
        provisioning-profiles:
          type: string
          default: ""
          description: "A Provisioning Profile allows you to install apps onto your iOS device and includes the signing certificates,
          a list of supported device identifiers, entitlements, and an App ID."
        entitlements:
          type: string
          default: ""
          description: "A plist file with the entitlements used for the application. Can be obtained from the Derived Data folder in Xcode"
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - appdome-orb/appdome_runner:
            runner: <<parameters.runner>>
            appFile: <<parameters.appFile>>
            output: <<parameters.output>>
            fusion-set-id: <<parameters.fusion-set-id>>
            signing-fingerprint: <<parameters.signing-fingerprint>>
            google-play-signing: false
            filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: appdome/appdome-orb
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0
