version: 2.1
orbs:
  appdome-orb: appdome/build-2secure@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  fixed tests:
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      - run: |
          ls .


workflows:
  test-deploy:
        # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
    jobs:
      - appdome-orb/appdome_runner:
          name: "test-android-auto-sign"
          runner: "ANDROID_AUTO_SIGNING"
          team-id: "81bdde00-a0a7-11ed-a4f2-810d8884a7b1"
          appFile: "https://github.com/idanhauser/TestAppdome_orb_private/raw/main/files/TimeCard1.apk"
          output: "appname.apk"
          filters: *filters
      - command-tests:
          filters: *filters
          requires:
           - ls_to_appdome_workspace

      # - appdome-orb/appdome_runner:
      #     name: "test-android-private-sign"
      #     runner: "ANDROID_PRIVATE_SIGNING"
      #     team-id: "81bdde00-a0a7-11ed-a4f2-810d8884a7b1"
      #     appFile: "https://github.com/idanhauser/TestAppdome_orb_private/raw/main/files/EmptyApp.apk"
      #     output: "appname.apk"
      #     filters: *filters
      # - appdome-orb/appdome_runner:
      #     name: "test-android-autodev-private-sign"
      #     runner: "ANDROID_AUTO_DEV_SIGNING"
      #     team-id: "81bdde00-a0a7-11ed-a4f2-810d8884a7b1"
      #     appFile: "https://github.com/idanhauser/TestAppdome_orb_private/raw/main/files/AndroidMediaPlayer.apk"
      #     output: "appname.apk"
      #     filters: *filters
      # - appdome-orb/appdome_runner:
      #     name: "test-ios-auto-sign"
      #     runner: "IOS_AUTO_SIGNING"
      #     team-id: "81bdde00-a0a7-11ed-a4f2-810d8884a7b1"
      #     appFile: "https://github.com/idanhauser/TestAppdome_orb_private/raw/main/files/FileFinder.ipa"
      #     output: "appname.ipa"
      #     filters: *filters
      # - appdome-orb/appdome_runner:
      #     name: "test-ios-private-sign"
      #     runner: "IOS_PRIVATE_SIGNING"
      #     team-id: "81bdde00-a0a7-11ed-a4f2-810d8884a7b1"
      #     appFile: "https://github.com/idanhauser/TestAppdome_orb_private/raw/main/files/Trends256-ForWatchKit.ipa"
      #     output: "appname.ipa"
      #     filters: *filters
      # - appdome-orb/appdome_runner:
      #     name: "test-ios-autodev-private-sign"
      #     runner: "IOS_AUTO_DEV_SIGNING"
      #     team-id: "81bdde00-a0a7-11ed-a4f2-810d8884a7b1"
      #     appFile: "https://github.com/idanhauser/TestAppdome_orb_private/raw/main/files/Trends_ios15.ipa"
      #     output: "appname.ipa"
      #     filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: appdome/build-2secure
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            # - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0
